### ISSUE TITLE
Proposed API

### ISSUE THREAD

**Issue by bcongdon** [acm-uiuc/groot-notification-service#1]
Routes:
- POST `/notifications/twitter`
- POST `/notifications/slack`
- POST `/notifications/email`

Request Body:
```
{
    'to': 'recipient', # only applicable for email/slack
    'from': 'sender', # only applicable for email
    'message': 'message body text'
}
```

**Comment by narendasan** [comment]
Should the channel be a parameter rather than a route. Like what if I want to send both a slack and a tweet?

**Comment by bcongdon** [comment]
I was thinking that too, and that's definitely one way of doing it. Do you think it will be common to post a notification to multiple services?

**Comment by aashishkapur** [comment]
It could be common to want to use both slack and twitter, such as "Event in the office in 10 minutes," but I don't think anyone would want to email and tweet the same message.

**Comment by sameetandpotatoes** [comment]
Hmm, for event reminders it makes sense to post to multiple services (i.e slack / twitter).

**Comment by bcongdon** [comment]
Maybe it would make sense to distinguish between messages and notifications?

i.e. twitter and slack (posting to a channel) are [global] notifications, whereas email is a message?

**Comment by aashishkapur** [comment]
I don't think it really makes sense.  With the above model, all the service would have to do is specify both slack and twitter

**Comment by aashishkapur** [comment]
The 'to' field should be a list, right, since we may want to send an email to multiple users.  Also, in the case of sending a message to slack and email, how do we distinguish between slack channels and email addresses?

**Comment by bcongdon** [comment]
Emails and slack channels could be regexed (i.e. `a@b.c` vs `#a`).

But, I don't like the idea of having recipients for multiple services in the same field.

**Comment by bcongdon** [comment]
If we really think we'll need to be sending notifications to multiple services in the same call, I'd propose allowing a bulk post to the notification endpoint:

```
[
    {'service': 'slack', 'to': '#general', 'message': 'Clean up the office'},
    {
        'service': 'email',
        'to': ['foo@acm.illinois.edu', 'bar@acm.illinois.edu'],
        'message': 'Clean up the office'
    },
]
```

**Comment by sameetandpotatoes** [comment]
The last approach does seem to be the most verbose (specifying same message twice), but also the most clear.

Perhaps the message could be refactored outside of the individual json?:

```
[
    {
       {'service': 'slack', 'to': '#general'},
       {
           'service': 'email',
           'to': ['foo@acm.illinois.edu', 'bar@acm.illinois.edu']
       },
      'message': 'Clean up the office'
    }
]
```

**Comment by bcongdon** [comment]
Yeah, I like that.
Something like: 
```
{
    'services': [
        {
            'service': 'slack',
            'to': '#general'
        },
        {
            'service': 'email',
            'to': ['foo@acm.illinois.edu', 'bar@acm.illinois.edu'],
        }
    ],
    'message': 'Clean up the office'
}
```

**Comment by sameetandpotatoes** [comment]
Initial design merged
